method: uika
dim: 1024
heads: 16
depth: 12  # must be divisible by 4
max_img_per_gpu: 16
max_batch: 8
image_num: [1, 16]
other_views: 8
num_workers: 8
ckpt_save_step: 5000
img_log_step: 2500

experiment:
    type: ${method}
    seed: 42
    parent: ${method}
    child: base

model:
    # image encoder
    encoder_type: "dinov3_fusion"
    encoder_model_name: "dinov3_vitl16"
    encoder_feat_dim: ${dim}
    encoder_freeze: true
    encoder_pretrained: true

    # transformer
    transformer_dim: ${dim}
    transformer_heads: ${heads}
    transformer_layers: ${depth}
    tf_grad_ckpt: true
    encoder_grad_ckpt: true

    # uv setting
    uv_token_size: 96
    uv_token_dim: ${dim}
    uv_attr_map_size: 384  # Expected size: model.uv_token_size * 4
    fuvt_ckpt_path: "./model_zoo/uv_modules/fuvt_15k.safetensors"
    fuvt_load_pretrained: true
    fuvt_pretrained_patch_embed: true

    # gs decoder
    cano_shape: true
    uv_dpt_inner_dim: 256
    gs_decode_dim: 512
    gs_xyz_offset_max_step: 0.2
    gs_clip_scaling: 0.01
    gs_mlp_network_config:
        n_neurons: 512
        n_hidden_layers: 2
        activation: silu
    scale_sphere: false
    fix_opacity: false
    fix_rotation: false
    gs_type: "3dgs"
    rot_type: "quat"
    
    # for gs renderer
    human_model_path: "./model_zoo/human_parametric_models"
    gs_use_rgb: True
    gs_sh: 0
    shape_param_dim: 300
    expr_param_dim: 100
    add_teeth: false
    teeth_bs_flag: false
    oral_mesh_flag: false

data:
    subsets:
        -   name: mv_video_head
            root_dirs: "./train_data/nersemble_v2/export"
            meta_path:
                train: "./train_data/nersemble_v2/label/train_ids.json"
                val: "./train_data/nersemble_v2/label/val_ids.json"
            sample_rate: 1.0
        
        -   name: mv_video_head
            root_dirs: "./train_data/vfhq/export"
            meta_path:
                train: "./train_data/vfhq/label/train_ids.json"
                val: "./train_data/vfhq/label/val_ids.json"
            sample_rate: 1.0
        
        -   name: mv_video_head
            root_dirs: "./train_data/hdtf/export"
            meta_path:
                train: "./train_data/hdtf/label/train_ids.json"
                val: "./train_data/hdtf/label/val_ids.json"
            sample_rate: 1.0
        
        -   name: mv_video_head
            root_dirs: "./train_data/synth_mv/export"
            meta_path:
                train: "./train_data/synth_mv/label/train_ids.json"
                val: "./train_data/synth_mv/label/val_ids.json"
            sample_rate: 1.0

    dataset:
        sample_side_views: ${other_views}
        source_image_res: 512
        render_image:
            low: 512
            high: 512
            region: null
        repeat_num: 1
        aspect_standard: 1.0
        enlarge_ratio: [0.8, 1.2]
    loader:
        max_img_per_gpu: ${max_img_per_gpu}
        max_batch: ${max_batch}
        image_num: ${image_num}
        num_workers: ${num_workers}
        shuffle: true
        pin_memory: true
        persistent_workers: false
        drop_last: true

train:
    mixed_precision: bf16  # REPLACE THIS BASED ON GPU TYPE
    find_unused_parameters: false
    loss:
        pixel_weight: 1.0
        pixel_loss_fn: "l1"  # "mse"
        crop_face_weight: 0.
        crop_mouth_weight: 50.
        crop_eye_weight: 0.
        perceptual_weight: 0.5  # use double lpips loss, ori_weight: 1.0
        ssim_weight: 0.1
        surfel_normal_weight: 0.05
        surfel_normal_step: 7000
        surfel_dist_weight: 100.
        surfel_dist_step: 3000
        tv_weight: -1
        mask_weight: 0:1.0:0.5:10000  # start_step:start_weight:end_weight:end_step
        offset_reg_weight: 0.1
        offset_sigma: 0.0
        opacity_entropy_weight: 5e-2
        opacity_entropy_eps: 1e-6
    optim:
        lr: 4e-4
        weight_decay: 0.05
        beta1: 0.9
        beta2: 0.95
        clip_grad_norm: 1.0
    scheduler:
        type: cosine
        warmup_real_iters: 3000
    batch_size: 4  # REPLACE THIS (PER GPU)
    accum_steps: 1  # REPLACE THIS
    epochs: 1000  # REPLACE THIS
    debug_global_steps: null
    resume: ""

val:
    batch_size: 2
    global_step_period: ${img_log_step}
    debug_batches: 10

saver:
    auto_resume: true
    load_model: null
    checkpoint_root: ./exps/checkpoints
    checkpoint_global_steps: ${ckpt_save_step}
    checkpoint_keep_level: 5

logger:
    stream_level: WARNING
    log_level: INFO
    log_root: ./exps/logs
    tracker_root: ./exps/trackers
    img_log_root: ./exps/img_logs
    enable_profiler: false
    trackers:
        - tensorboard
    image_monitor:
        train_global_steps: ${img_log_step}
        samples_per_log: 4

compile:
    suppress_errors: true
    print_specializations: true
    disable: true
